CREATE SEQUENCE IF NOT EXISTS room_number_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20)  NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS rooms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(50)  NOT NULL UNIQUE,
    room_name   VARCHAR(100) NOT NULL,
    creator_id  BIGINT       NOT NULL,
    max_members INT          NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_rooms (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT    NOT NULL,
    room_id   BIGINT    NOT NULL,
    joined_at TIMESTAMP NOT NULL,
    UNIQUE (user_id, room_id)
);

CREATE TABLE IF NOT EXISTS locations (
     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     user_id     BIGINT           NOT NULL,
     latitude    DOUBLE PRECISION NOT NULL,
     longitude   DOUBLE PRECISION NOT NULL,
     recorded_at TIMESTAMP        NOT NULL
);
